---
# tasks file for k8s-cluster
- name: "Installing docker and iproute-tc"
  package: 
     name:
         - docker
         - iproute-tc
     state: present
- name: "Configuring the Yum repo for kubernetes"
  yum_repository:
     name: kubernetes
     description: Yum for k8s
     baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
     enabled: yes
     gpgcheck: yes
     repo_gpgcheck: yes
     gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
- name: "Installing kubeadm,kubelet kubectl program"
  yum:
     name:
        - kubelet
        - kubectl
        - kubeadm
     state: present
- name: "Enabling the docker and kubenetes"
  service:
     name: "{{ item }}"
     state: started
     enabled: yes
  loop:
        - kubelet
        - docker
- name: "Pulling the config images"
  shell: "kubeadm config images pull"
  changed_when: false
      
- name: "Confuring the docker daemon.json file"
  copy:
     dest: /etc/docker/daemon.json
     src: daemon.json
- name: "Restarting the docker service"
  service:
     name: docker
     state: restarted
- name: "Configuring the Ip tables and refreshing sysctl"
  copy:
     dest: /etc/sysctl.d/iptables-1.conf
     src: iptables-1.conf
- name: "systemctl"
  shell: "sysctl --system"
- name: "Starting kubeadm service"
  shell: "kubeadm init --pod-network-cidr={{ ipp }} --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"
  register: init

- name: "Creating .kube Directory"
  shell: "sudo mkdir -p $HOME/.kube"

- name: "Copying file config file"
  shell: "sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"

- name: "Changing the owner permissions"
  shell: "sudo chown $(id -u):$(id -g) $HOME/.kube/config"

- name: "Installing Addons e.g flannel"
  shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"

- name: "Creating the token"
  shell: "kubeadm token create --print-join-command"
  register: tokens
  ignore_errors: yes

- debug:
     var: tokens.stdout_lines
  register: tokens
